import os
import ast
from typing import List, Tuple
from .schema import Node, Edge, NodeType, EdgeType

class Inspector:
    def is_generated(self, file_path: str, content: str = None) -> bool:
        """Heuristic to check if a file is generated."""
        # 1. Extension check
        if file_path.endswith(('_pb2.py', '_grpc.py', '.min.js', '.map')):
            return True
        
        # 2. Content check (read first few lines)
        if content is None:
            try:
                with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                    content = f.read(1024) # Read first 1KB
            except:
                return False
        
        markers = [
            'DO NOT EDIT', 
            'Generated by', 
            'This file is auto-generated', 
            'Code generated by'
        ]
        
        for marker in markers:
            if marker.lower() in content.lower():
                return True
        
        return False

    def inspect_file(self, file_path: str) -> Tuple[List[Node], List[Edge]]:
        # Check generated status first
        is_generated = self.is_generated(file_path)
        
        nodes, edges = [], []
        
        if file_path.endswith('.py'):
            nodes, edges = self.inspect_python_file(file_path)
        elif file_path.endswith('.ipynb'):
            file_node = self._create_file_node(file_path, 'jupyter')
            nodes.append(file_node)
            cell_nodes, cell_edges = self.inspect_notebook(file_path, file_node)
            nodes.extend(cell_nodes)
            edges.extend(cell_edges)
        elif file_path.endswith('.js') or file_path.endswith('.jsx') or file_path.endswith('.ts'):
            nodes, edges = self.inspect_javascript_file(file_path)
        elif file_path.endswith(('.c', '.h', '.cpp', '.hpp')):
            nodes, edges = self.inspect_c_file(file_path)
        elif file_path.endswith('.json'):
            file_node = self._create_file_node(file_path, 'json')
            nodes.append(file_node)
            n, e = self.inspect_json(file_path, file_node)
            nodes.extend(n)
            edges.extend(e)
        elif file_path.endswith('.html') or file_path.endswith('.htm'):
            file_node = self._create_file_node(file_path, 'html')
            nodes.append(file_node)
            n, e = self.inspect_html(file_path, file_node)
            nodes.extend(n)
            edges.extend(e)
        elif file_path.endswith('.css'):
            file_node = self._create_file_node(file_path, 'css')
            nodes.append(file_node)
            n, e = self.inspect_css(file_path, file_node)
            nodes.extend(n)
            edges.extend(e)
        
        # Mark all file nodes as generated if detected
        if is_generated:
            for node in nodes:
                if node.type == NodeType.FILE:
                    node.metadata['generated'] = True
                    
        return nodes, edges

    def inspect_python_file(self, file_path: str) -> Tuple[List[Node], List[Edge]]:
        nodes: List[Node] = []
        edges: List[Edge] = []
        
        file_node = Node(
            id=file_path,
            type=NodeType.FILE,
            name=os.path.basename(file_path),
            metadata={'path': file_path, 'language': 'python'}
        )
        nodes.append(file_node)

        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
                tree = ast.parse(content, filename=file_path)
        except Exception as e:
            print(f"Error parsing {file_path}: {e}")
            return nodes, edges

        ast_nodes, ast_edges = self._extract_ast_nodes(tree, file_path, file_node)
        nodes.extend(ast_nodes)
        edges.extend(ast_edges)
        return nodes, edges

    def _extract_ast_nodes(self, tree: ast.AST, file_path: str, file_node: Node, metadata_override: dict = None) -> Tuple[List[Node], List[Edge]]:
        nodes = []
        edges = []
        
        def visit(node, parent_id, namespace_prefix):
            # Iterate over fields to find nested blocks (body, etc.)
            # But specific handling for Class/Func is cleaner
            
            # recursive children traversal helper
            def visit_children(parent_node_id, current_prefix):
                 for child in ast.iter_child_nodes(node):
                     visit(child, parent_node_id, current_prefix)

            def calculate_complexity(node):
                """Calculates Cyclomatic Complexity (McCabe)."""
                complexity = 1
                for child in ast.walk(node):
                    if isinstance(child, (ast.If, ast.For, ast.AsyncFor, ast.While, ast.With, ast.AsyncWith, ast.ExceptHandler)):
                        complexity += 1
                    elif isinstance(child, ast.BoolOp):
                        # count 'and' / 'or' as branches
                        complexity += len(child.values) - 1
                return complexity

            metadata = {'lineno': getattr(node, 'lineno', 0)}
            if metadata_override:
                metadata.update(metadata_override)

            if isinstance(node, ast.Module):
                # Root, just visit children with file_id
                visit_children(parent_id, namespace_prefix)

            elif isinstance(node, ast.ClassDef):
                # Extract base classes
                bases = []
                for base in node.bases:
                    if isinstance(base, ast.Name):
                        bases.append(base.id)
                    elif isinstance(base, ast.Attribute):
                        bases.append(f"{base.value.id}.{base.attr}" if isinstance(base.value, ast.Name) else base.attr)
                
                metadata['bases'] = bases
                metadata['docstring'] = ast.get_docstring(node)
                metadata['complexity'] = calculate_complexity(node)
                
                node_id = f"{namespace_prefix}::{node.name}"
                class_node = Node(
                    id=node_id,
                    type=NodeType.CLASS,
                    name=node.name,
                    metadata=metadata
                )
                nodes.append(class_node)
                edges.append(Edge(source_id=parent_id, target_id=class_node.id, type=EdgeType.DEFINES))
                
                # Visit children with class as parent
                # Update prefix for children? Yes
                # Actually ast.iter_child_nodes yields bases/decorators too, we mostly care about body
                for child in node.body:
                    visit(child, class_node.id, node_id)

            elif isinstance(node, ast.FunctionDef) or isinstance(node, ast.AsyncFunctionDef):
                # Extract arguments
                args = []
                for arg in node.args.args:
                    arg_name = arg.arg
                    arg_type = None
                    if arg.annotation:
                        if isinstance(arg.annotation, ast.Name):
                            arg_type = arg.annotation.id
                        elif isinstance(arg.annotation, ast.Constant):
                            arg_type = str(arg.annotation.value)
                        else:
                            try:
                                arg_type = ast.unparse(arg.annotation)
                            except:
                                arg_type = "Any"
                    args.append({'name': arg_name, 'type': arg_type})
                
                # Extract return type
                return_type = None
                if node.returns:
                    if isinstance(node.returns, ast.Name):
                        return_type = node.returns.id
                    elif isinstance(node.returns, ast.Constant): 
                        return_type = str(node.returns.value)
                    else:
                        try:
                            return_type = ast.unparse(node.returns)
                        except:
                            return_type = "Any"

                metadata['args'] = args
                metadata['returns'] = return_type
                metadata['docstring'] = ast.get_docstring(node)
                metadata['complexity'] = calculate_complexity(node)

                node_id = f"{namespace_prefix}::{node.name}"
                func_node = Node(
                    id=node_id,
                    type=NodeType.FUNCTION,
                    name=node.name,
                    metadata=metadata
                )
                nodes.append(func_node)
                edges.append(Edge(source_id=parent_id, target_id=func_node.id, type=EdgeType.DEFINES))
                
                # Visit inner functions/classes
                for child in node.body:
                    visit(child, func_node.id, node_id)

            elif isinstance(node, ast.Import):
                for name in node.names:
                    # Link imports to the scope they are defined in (file, class, or func)
                    import_name = name.name
                    target_id = f"module::{import_name}"
                    edges.append(Edge(source_id=parent_id, target_id=target_id, type=EdgeType.IMPORTS))

            elif isinstance(node, ast.ImportFrom):
                module = node.module or ''
                for name in node.names:
                    full_name = f"{module}.{name.name}" if module else name.name
                    target_id = f"module::{full_name}"
                    edges.append(Edge(source_id=parent_id, target_id=target_id, type=EdgeType.IMPORTS))
            
            elif isinstance(node, ast.Call):
                # Detect calls: func(), self.method()
                target_name = None
                if isinstance(node.func, ast.Name):
                    target_name = node.func.id
                elif isinstance(node.func, ast.Attribute):
                    target_name = node.func.attr
                
                if target_name:
                    # We don't know the exact target node ID easily without type inference,
                    # so we create a heuristic target ID.
                    # The CLI or Reporter can then try to match it.
                    # For now, let's just use the name as a partial ID or look it up.
                    # A better way is to use a search-friendly ID.
                    target_id = f"sym::{target_name}"
                    edges.append(Edge(source_id=parent_id, target_id=target_id, type=EdgeType.CALLS))
                
                visit_children(parent_id, namespace_prefix)

            else:
                 # visit children for other nodes (If, Try, etc) to find nested definitions
                 # Propagate parent_id
                 visit_children(parent_id, namespace_prefix)

        visit(tree, file_node.id, file_path)
        return nodes, edges

    def inspect_notebook(self, file_path: str, file_node: Node) -> Tuple[List[Node], List[Edge]]:
        nodes: List[Node] = []
        edges: List[Edge] = []
        import json
        
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                nb_data = json.load(f)
        except Exception as e:
            print(f"Error reading notebook {file_path}: {e}")
            return nodes, edges

        cells = nb_data.get('cells', [])
        for i, cell in enumerate(cells):
            if cell.get('cell_type') == 'code':
                # Concatenate source lines
                source = "".join(cell.get('source', []))
                if not source.strip(): continue
                
                # Parse AST
                try:
                    tree = ast.parse(source, filename=file_path)
                    # Create a virtual "Cell" node? Or just map metadata?
                    # Let's add metadata to symbols
                    cell_metadata = {'cell_index': i, 'language': 'python'}
                    
                    cell_nodes, cell_edges = self._extract_ast_nodes(tree, file_path, file_node, metadata_override=cell_metadata)
                    nodes.extend(cell_nodes)
                    edges.extend(cell_edges)
                    
                except SyntaxError:
                    pass # Magic commands or non-python code
                    
        return nodes, edges

    def inspect_json(self, file_path: str, file_node: Node) -> Tuple[List[Node], List[Edge]]:
        # Just return the file node, maybe edges if we decide to parse dependencies later (e.g. package.json)
        return [], []

    def inspect_javascript_file(self, file_path: str) -> Tuple[List[Node], List[Edge]]:
        import re
        nodes: List[Node] = []
        edges: List[Edge] = []
        file_node = self._create_file_node(file_path, 'javascript')
        nodes.append(file_node)
        
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
        except:
            return nodes, edges

        # Regex for functions: function name( or class Name
        # Very pervasive, basic support
        
        # function myFunc(
        func_pattern = re.compile(r'function\s+([a-zA-Z0-9_]+)\s*\(')
        for match in func_pattern.finditer(content):
            name = match.group(1)
            nodes.append(Node(id=f"{file_path}::{name}", type=NodeType.FUNCTION, name=name, metadata={'lineno': content[:match.start()].count('\n') + 1}))
            edges.append(Edge(source_id=file_node.id, target_id=f"{file_path}::{name}", type=EdgeType.DEFINES))

        # const myFunc = () =>
        arrow_pattern = re.compile(r'(const|let|var)\s+([a-zA-Z0-9_]+)\s*=\s*(\(.*\)|[a-zA-Z0-9_]+)\s*=>')
        for match in arrow_pattern.finditer(content):
            name = match.group(2)
            nodes.append(Node(id=f"{file_path}::{name}", type=NodeType.FUNCTION, name=name, metadata={'lineno': content[:match.start()].count('\n') + 1}))
            edges.append(Edge(source_id=file_node.id, target_id=f"{file_path}::{name}", type=EdgeType.DEFINES))
            
        # class MyClass
        class_pattern = re.compile(r'class\s+([a-zA-Z0-9_]+)')
        for match in class_pattern.finditer(content):
            name = match.group(1)
            nodes.append(Node(id=f"{file_path}::{name}", type=NodeType.CLASS, name=name, metadata={'lineno': content[:match.start()].count('\n') + 1}))
            edges.append(Edge(source_id=file_node.id, target_id=f"{file_path}::{name}", type=EdgeType.DEFINES))

        # Function Calls (Heuristic)
        call_pattern = re.compile(r'\b([a-zA-Z0-9_]+)\s*\(')
        js_keywords = {'if', 'while', 'for', 'switch', 'return', 'function', 'catch', 'await', 'new', 'console', 'log', 'assert'}
        for match in call_pattern.finditer(content):
            name = match.group(1)
            if name not in js_keywords:
                edges.append(Edge(source_id=file_node.id, target_id=f"sym::{name}", type=EdgeType.CALLS))

        return nodes, edges

    def inspect_c_file(self, file_path: str) -> Tuple[List[Node], List[Edge]]:
        import re
        nodes: List[Node] = []
        edges: List[Edge] = []
        file_node = self._create_file_node(file_path, 'c')
        nodes.append(file_node)
        
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
        except:
            return nodes, edges

        # Basic C function definition: ReturnType Name(Args) {
        # This is hard with regex, so we'll approximate: Name(
        # avoiding "if (", "while (", "for ("
        
        # Matches: void func_name(
        # Excludes: if, while, for, switch, return
        func_pattern = re.compile(r'\b([a-zA-Z0-9_]+)\s*\([^;]*\)\s*\{')
        keywords = {'if', 'while', 'for', 'switch', 'return', 'catch'}
        
        for match in func_pattern.finditer(content):
            name = match.group(1)
            if name in keywords: continue
            
            nodes.append(Node(id=f"{file_path}::{name}", type=NodeType.FUNCTION, name=name, metadata={'lineno': content[:match.start()].count('\n') + 1}))
            edges.append(Edge(source_id=file_node.id, target_id=f"{file_path}::{name}", type=EdgeType.DEFINES))
            
        # Function Calls (Heuristic)
        call_pattern = re.compile(r'\b([a-zA-Z0-9_]+)\s*\(')
        c_keywords = {'if', 'while', 'for', 'switch', 'return', 'catch', 'sizeof', 'printf', 'scanf', 'malloc', 'free'}
        for match in call_pattern.finditer(content):
            name = match.group(1)
            if name not in c_keywords and name not in keywords: # Combine with original keywords list if it existed? Wait, keywords was local to inspect_c_file
                 # The code had: keywords = {'if', 'while', 'for', 'switch', 'return', 'catch'}
                 if name not in c_keywords:
                     edges.append(Edge(source_id=file_node.id, target_id=f"sym::{name}", type=EdgeType.CALLS))

        return nodes, edges

    def inspect_html(self, file_path: str, file_node: Node) -> Tuple[List[Node], List[Edge]]:
        # Regex for <script src="..."> and <link href="...">
        import re
        edges: List[Edge] = []
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
        except:
            return [], []

        # JS Links
        script_pattern = re.compile(r'<script\s+(?:[^>]*?\s+)?src=["\']([^"\']+)["\']')
        for match in script_pattern.finditer(content):
            src = match.group(1)
            target_id = f"file::{src}" # Naive
            edges.append(Edge(source_id=file_node.id, target_id=target_id, type=EdgeType.IMPORTS))

        # CSS Links
        css_pattern = re.compile(r'<link\s+(?:[^>]*?\s+)?href=["\']([^"\']+)["\']')
        for match in css_pattern.finditer(content):
            href = match.group(1)
            target_id = f"file::{href}"
            edges.append(Edge(source_id=file_node.id, target_id=target_id, type=EdgeType.IMPORTS))
            
        return [], edges

    def inspect_css(self, file_path: str, file_node: Node) -> Tuple[List[Node], List[Edge]]:
        # Regex for @import
        import re
        edges: List[Edge] = []
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
        except:
            return [], []

        import_pattern = re.compile(r'@import\s+["\']([^"\']+)["\']')
        for match in import_pattern.finditer(content):
            src = match.group(1)
            target_id = f"file::{src}"
            edges.append(Edge(source_id=file_node.id, target_id=target_id, type=EdgeType.IMPORTS))
            
        return [], edges

    def _create_file_node(self, file_path, language):
        return Node(
            id=file_path,
            type=NodeType.FILE,
            name=os.path.basename(file_path),
            metadata={'path': file_path, 'language': language}
        )
